name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test on .NET ${{ matrix.dotnet }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet: [ '6.0.301' ]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Install dependencies
        run: dotnet restore src/ChuckDeviceController.sln
      - name: Build project
        run: dotnet build src/ChuckDeviceController.sln
